"""initial schema

Revision ID: 9f587cfcbe9b
Revises: 
Create Date: 2026-06-06 08:55:16.400545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f587cfcbe9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=True),
    sa.Column('gst_percent', sa.Numeric(), server_default='18', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_logo', sa.Text(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('venue_type', sa.Text(), nullable=False),
    sa.Column('venue_address', sa.Text(), server_default='', nullable=True),
    sa.Column('event_date', sa.Text(), nullable=False),
    sa.Column('event_time', sa.Text(), nullable=False),
    sa.Column('event_end_time', sa.Text(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('discount_amount', sa.Numeric(), server_default='0', nullable=True),
    sa.Column('discount_percent', sa.Numeric(), server_default='0', nullable=True),
    sa.Column('transportation_cost', sa.Numeric(), server_default='0', nullable=True),
    sa.Column('advance_paid', sa.Numeric(), server_default='0', nullable=True),
    sa.Column('gst_percent', sa.Numeric(), server_default='18', nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=True),
    sa.Column('status', sa.Text(), server_default='booked', nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_branch_date', 'bookings', ['branch_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_bookings_branch_id'), 'bookings', ['branch_id'], unique=False)
    op.create_index(op.f('ix_bookings_event_date'), 'bookings', ['event_date'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_branch_id'), 'categories', ['branch_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'role', name='users_username_role_unique')
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_branch_id'), 'menu_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    # ### end Alembic commands ###

    # ----- Row Level Security -----
    # Enable RLS on every table. With no permissive policies, the anon and
    # authenticated Supabase roles can do nothing through PostgREST/Supabase
    # client — i.e. branch data cannot leak via the public API.
    #
    # The FastAPI backend connects as the privileged `postgres` user (table
    # owner) via the transaction pooler and therefore bypasses RLS. Branch
    # isolation for managers/staff is enforced in application code (see
    # require_role and branch_id filters in server.py); admin queries bypass
    # the application-level filters and see every branch.
    for tbl in ("branches", "users", "categories", "menu_items", "bookings", "settings"):
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_branch_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_branch_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_branch_id'), table_name='bookings')
    op.drop_index('ix_bookings_branch_date', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('settings')
    op.drop_table('branches')
    # ### end Alembic commands ###
